import { readFile, writeFile } from 'node:fs/promises';
const root = new URL('../', import.meta.url);
const fields = await Promise.all(['index.html', 'app.css', 'app.js'].map(name => readFile(new URL(`ui/${name}`, root), 'utf8')));
await writeFile(new URL('generated-ui.mjs', root), `// Generated by scripts/build-ui.mjs.\nexport const HTML = ${JSON.stringify(fields[0])};\nexport const CSS = ${JSON.stringify(fields[1])};\nexport const JS = ${JSON.stringify(fields[2])};\n`);
